version: '2'  # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:  # containers. same as docker run
  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - d-modules:/var/www/html/modules
      - d-profiles:/var/www/html/profiles
      - d-themes:/var/www/html/themes
      - d-sites:/var/www/html/sites
  
  db: # a friendly name. this is also DNS name inside network
    image: postgres:10 # Optional if you use build:
    environment: 
      POSTGRES_PASSWORD: MyPassWord # Optional, same as -e in docker run
    volumes: 
      - db_vol:/var/lib/postgresql/data # Optional, same as -v in docker run
  
volumes:
  db_vol:
  d-modules:
  d-profiles:
  d-themes:
  d-sites:
